name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          cd backend
          npm install
          npm run build --if-present

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: techin515
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: backend/dist
