name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install
        working-directory: backend

      - name: Generate Prisma client
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma generate
        working-directory: backend

      - name: Apply database migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx prisma migrate deploy
        working-directory: backend

      - name: Build the project
        run: npm run build
        working-directory: backend

      - name: Archive the build files
        run: zip -r ../backend.zip *
        working-directory: backend/dist

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: techin515
          package: backend.zip
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Restart Azure App Service
        run: |
          az webapp restart --name techin515 --resource-group your-resource-group
        env:
          AZURE_WEBAPP_NAME: techin515
          AZURE_RESOURCE_GROUP: your-resource-group
          AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
